version: "3"
services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel
        working_dir: /app
        volumes:
            - ./:/app
    web:
        image: nginx
        container_name: web
        depends_on:
            - laravel
        ports:
            - 8000:80
        volumes:
            - ./:/app
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    db:
        image: mariadb:10.2
        container_name: db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3313:3306
        volumes:
            - db:/var/lib/mysql
volumes:
    db:
